services:
  mongodb:
    image: mongo:7.0
    container_name: video_annotator_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongod.conf:/etc/mongod.conf:ro
      - ./logs/mongodb:/var/log/mongodb
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  mongo-express:
    image: mongo-express:latest
    container_name: video_annotator_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD:-password}
    depends_on:
      - mongodb

  redis:
    image: redis:7.2-alpine
    container_name: video_annotator_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: video_annotator_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: video_annotator_celery
    restart: unless-stopped
    command: celery -A backend.background_tasks.app worker --loglevel=info --concurrency=4
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: video_annotator_flower
    restart: unless-stopped
    command: celery -A backend.background_tasks.app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data: